# .github/workflows/sync.yml
name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # 每小时 0分触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
      run: echo Hello,github action!
