name: Update Time

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "RikkaBunny"
          git config --global user.email "nextjs-notion-starter-kit"

      - name: Update time
        run: |
          echo $(date) > time.txt
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ github.token }}
